### ISSUE TITLE
unit tests shouldn't require docker

### ISSUE THREAD

**Issue by paulczar** [kbastani/event-sourcing-microservices-example#24]
There's many situations in which somebody may want to run `mvn test` without docker installed, currently a lot of the tests are wired up to use docker images for database etc, we should be able to use in-memory ones (H2 for postgres, etc ) and remove the hard requirement on docker for basic unit testing.

**Comment by kbastani** [comment]
TODO: Reminder to attribute @bsideup in the test container classes.

**Comment by bsideup** [comment]
@kbastani I appreciate it, but no need to ☺️

**Comment by kbastani** [comment]
What if people come asking questions!? :-)

**Comment by bsideup** [comment]
@kbastani figure it out! You are ~~the Architecture CTO~~ an engineer :D

**Comment by kbastani** [comment]
😝

**Comment by kbastani** [comment]
I am going to close this issue. The example project does require docker.
