### ISSUE TITLE
Helm Chart not working

### ISSUE THREAD

**Issue by mbell-gresham** [kbastani/event-sourcing-microservices-example#31]
`C:\projects\event-sourcing-microservices-example>helm dep update deployment/helm/social-network
Error: error unpacking edge-service in social-network: chart metadata (Chart.yaml) missing`

In order to get this to work, I had to move each of the child charts, inside the social-network/charts folder, and remove the files present

Helm version:
```C:\Windows\system32>helm version
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}```

**Comment by danielsurowiec** [comment]
Submited #32 that fixed dep update issue for me.

**Comment by kbastani** [comment]
Thanks @dazerek
